### ISSUE TITLE
AutoFocus on negative tilts

### ISSUE THREAD

**Issue by hamid13r** [eisfabian/PACEtomo#12]
Hi Fabian,

We have been enjoying PACEtomo for a while in scripps and have come up with some issues with defocus values. We tried to refine the tilt axis offset and add autofocus to the tracking position which improved the defocus consistently significantly. However, I noticed the autofocus does not help in negative tilts. I looked at the script and seems like this line was the issue:

https://github.com/eisfabian/PACEtomo/blob/68e0e0b5de84b5000cedc570a36f2c5135eb38f9/PACEtomo.py#L225

and removing the last condition pretty much solved the issue for us. The series on the right are after the change was made to the script.
![image](https://user-images.githubusercontent.com/66981513/221470596-dd15bc8d-10f4-405f-bdd3-b79c1e1537bc.png)

I have tried adding an experimental slope once, but could not get consistent results. Any suggestions on using that feature could also be very useful for us, although I am quite happy with the output and the throughput with the autofocus step. 

Thanks,
Hamid

**Comment by eisfabian** [comment]
Dear Hamid,

Thanks so much! Yes, the last condition should indeed be:
`abs(tilt - startTilt) > step`
This is supposed to avoid an autofocus immediately after starting the TS.

But ideally you wouldn't want to use the addAF function in order to make the tracking tilt series usable.
Did you use the [PACEtomo_measureOffset.py](https://github.com/eisfabian/PACEtomo/blob/main/PACEtomo_measureOffset.py) script to refine the tilt axis offset? What kind of outputs did you get from it? I assume you are on a Krios?

The focus slope function should not be necessary anymore and I will remove it in a future version. 

Thanks again and best wishes,
Fabian

**Comment by hamid13r** [comment]
Thank you very much. We refined the offset a while back using a cross grating. If I remember correctly, we were getting pretty straight lines but the value was not super consistent in different parts of a grid so we used an average value. That lowered the range to ~2um from -60 to 60 degrees but didn't no solve the problem completely. At that point, we just started doing autofocus and sacrificing the tracking position to get better data.

By the way, it is on a Krios.


Best,
Hamid
