### ISSUE TITLE
pacetomo keeps collecting when column valves are closed

### ISSUE THREAD

**Issue by RHennellJames** [eisfabian/PACEtomo#26]
Hi Fabian,

We've recently had an issue where the octagon pressure on our Krios spikes very briefly so the column valves close. When this happens pacetomo keeps collecting and just adds a warning to the log (Possibly SerialEM adds this warning, not PACEtomo).

Is there a command we could add to the PACEtomo script that would use ReportColumnOrGunValve to check if the column valves are closed and pause collection if they are closed? It seems that the octagon pressure recovers quite quickly so if PACEtomo could wait 5 minutes and then open the valves and restart that would be really great.

Thanks,
Rory

**Comment by eisfabian** [comment]
Hi Rory,

You could add the following lines at the beginning of the ```checkFilling()``` function (line 99 in v1.7):

```
while sem.ReportColumnOrGunValve() < 1:
    sem.Delay(300, "s")
    sem.SetColumnOrGunValve(1)
```

It will try every 5 min to open the column valves. I'm not sure how the microscope behaves after the last command.
If it refuses to open when the vacuum is not good, this should be fine.
If it tries to open despite the vacuum and the close again, because of the vacuum, you might want to add another delay at the end to make sure the valves stay open before you continue acquisition.

Let me know if this helps!

Best,
Fabian

**Comment by RHennellJames** [comment]
Hi Fabian,

Thanks very much. An engineer is trying to fix the microscope issue today, but if that doesn't work we'll try adding this to the script instead.

Best,
Rory
